### ISSUE TITLE
Phase 0 Report

### ISSUE THREAD

**Issue by Sepehr-Noori** [advanced-programming-sut-2023/project-group-11#1]
<div dir="rtl" align='right'>

# فاز 0

## کارهایی که باید در فاز 0 انجام دهید

<details>
  <summary>راه‌اندازی مخزن GItHub</summary>

  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>

<details>
  <summary>راه‌اندازی GitHub Issue</summary>
  
  <div  dir="ltr" align='right'>
  
  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
     </div>
</details>

<details>
  <summary>طراحی UML برای منطق پروژه</summary>
  
  <div  dir="ltr" align='right'>
  
  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
     </div>
</details>

## تسک‌های نفر اول

  **صادق سرگران:**
<details>
  <summary>کامیت نام و شماره دانشجویی در README.md</summary>

  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>

</details>
<details>
  <summary>طراحی UML</summary>

  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>

</details>

## تسک‌های نفر دوم

  **سپهر نوری:**
<details>
  <summary>کامیت نام و شماره دانشجویی در README.md</summary>

  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>
<details>
  <summary>طراحی UML</summary>

  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>

</details>

## تسک‌های نفر سوم

  **امیررضا سعیدی:**
<details>
  <summary>کامیت نام و شماره دانشجویی در README.md</summary>

  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>
<details>
  <summary>طراحی UML</summary>

  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>

</details>

**Comment by Sadeghdrr** [comment]
> # فاز 0
> ## کارهایی که باید در فاز 0 انجام دهید
> راه‌اندازی مخزن GItHub
> راه‌اندازی GitHub Issue
> طراحی UML برای منطق پروژه
> ## تسک‌های نفر اول
> **صادق سرگران:**
> 
> کامیت نام شماره دانشجویی در README.md
> ## تسک‌های نفر دوم
> **سپهر نوری:**
> 
> کامیت نام و شماره دانشجویی در README.md
> ## تسک‌های نفر سوم
> **نام و نام خانوادگی:**
> 
> تسک مربوطه
